### ISSUE TITLE
多服务名称与驱动填写方式

### ISSUE THREAD

**Issue by linjifu** [yuntian001/multi-process-queue#1]
请问下如果是多分布式部署下，服务名称跟驱动那边如何填写配置，我看例子跟文档上面只写了单台服务器跟一句注释，望大佬解答下

**Comment by linjifu** [comment]
额~可能是我理解有点问题，这个是不是指链接redis同一个，项目部署多个

**Comment by yuntian001** [comment]
服务名称随便填写，保证每个服务名字唯一即可，服务名称的用意是为了把当前任务是哪台服务器的哪个进程执行的记录到redis以便于出错后根据服务名称去对应服务器查找日志。
驱动直接按例子填入默认的redis类即可，可以根据命名空间到对应的目录下找到驱动文件。里面有详细的参数说明
同一个队列多个服务器部署，redis和队列名称是需要同一个的。这样才能做的同一个队列分发到不同服务器。

**Comment by yuntian001** [comment]
> 额~可能是我理解有点问题，这个是不是指链接redis同一个，项目部署多个

对的，就是同一个redis 项目部署多个。

**Comment by yuntian001** [comment]
> 请问下如果是多分布式部署下，服务名称跟驱动那边如何填写配置，我看例子跟文档上面只写了单台服务器跟一句注释，望大佬解答下

服务名称随便填写，保证每个服务名字唯一即可，服务名称的用意是为了把当前任务是哪台服务器的哪个进程执行的记录到redis以便于出错后根据服务名称去对应服务器查找日志。
驱动直接按例子填入默认的redis类即可，可以根据命名空间到对应的目录下找到驱动文件。里面有详细的参数说明
同一个队列多个服务器部署，redis和队列名称是需要同一个的。这样才能做的同一个队列分发到不同服务器

**Comment by linjifu** [comment]
谢谢，明白了
