### ISSUE TITLE
thinkphp5.0框架下怎么创建一个定时任务呢

### ISSUE THREAD

**Issue by wuaidajiejie** [yuntian001/multi-process-queue#10]
可以用这个包创建一个秒级的定时任务吗？

**Comment by yuntian001** [comment]
当前系统只是队列，不是专门的定时任务系统，如果想在此系统实现定时任务可以用延时投递的方式去实现，在执行任务方法里计算好下次时间再次投递。定时还是建议用linux的系统定时或者专门的定时框架去实现。
