### ISSUE TITLE
持续运行了一个月中间发生的事件

### ISSUE THREAD

**Issue by shaozi17** [yuntian001/multi-process-queue#13]
![image](https://user-images.githubusercontent.com/22265868/206482080-f6114191-57e2-440f-8224-e71d9fd3b7b9.png)
![image](https://user-images.githubusercontent.com/22265868/206482359-d8fe1909-9c86-4eb9-9553-84b339b14810.png)
![image](https://user-images.githubusercontent.com/22265868/206482425-c041f3a6-12b0-43bc-98b3-cb46f56bc96b.png)
看样子是由redis连接断线之后发生的一连串进程退出。

**Comment by shaozi17** [comment]
![image](https://user-images.githubusercontent.com/22265868/206976482-d2c0b8f3-e0b9-4c09-b95c-6f8e3a6ca3c0.png)

**Comment by yuntian001** [comment]
应该是 woker 进程异常退出后master 进程无法与其通信抛出 异常，导致master进程也退出了。我修复一下
