### ISSUE TITLE
老哥你这个有点问题啊不能传参数

### ISSUE THREAD

**Issue by 577125419** [yuntian001/multi-process-queue#18]
例如要后台处理一万条订单的审批,可以在投递任务时把订单号或别的唯一标识传进去,在处理任务时传到handle方法里面,然后根据订单号查询数据库处理业务

**Comment by yuntian001** [comment]
投递时可以投递对象 需要传入的参数可以在对象的`__construct`函数传入 设置为对象的属性
```
    \MPQueue\Queue\Queue::push('test',new \App\Job\HelloWord([1,2,3,4]));
```

**Comment by 577125419** [comment]
原来可以这样,试了下ok了，我刚才还去改源码了push以及redis驱动那加了个data参数呢,谢谢,建议一下你下个版本可以加个删除方法,和重新入队方法，例如我有一条订单要修改状态,但是后台管理员或用户已经把这个订单删除取消了,我根据订单号判断这条订单已经失效,直接删除这条订单,现在只能业务执行成功的方式自动删掉任务，还有业务修改订单状态时数据库出问题修改失败可以重新入队,现在只能throw new \Exception让走fail_handle回调重新入队

**Comment by yuntian001** [comment]
队列是不可逆的，具体状态判断应该放在业务代码中，在队列执行时在业务代码中进行状态判断，对不同状态进行不同的操作。重新入队直接在队列执行代码中 重新投递一次即可，但要做好条件判断，否则容易进入死循环。

**Comment by 577125419** [comment]
ok,明白了,谢谢了
