### ISSUE TITLE
这个线程工作时是异步的吗

### ISSUE THREAD

**Issue by 577125419** [yuntian001/multi-process-queue#19]
是这样的，因为队列用来后台调用第三方接口的，人家的接口有qps限制，需要的是同步阻塞的队列，例如现在有一万个调用接口任务，我设置4工作线程，每次取出4个调用参数调用对方接口，调用完成后才取出下四个

**Comment by yuntian001** [comment]
每个worker进程 只会同时消费一个任务

**Comment by 577125419** [comment]
这个是不是每次直接把redis里面取出的任务多然后再分发任务,还是每次用的时候才从redis取，我每次往redis某个队列一次推送一万多任务,然后一启动没有一分钟任务就没有了,毕竟我调过第三方接口,每次调用也得快一秒时间,按理一工作线程的配置一万多任务也得几个小时才弄完，用过think-queue，处理5000任务要一个多小时

**Comment by yuntian001** [comment]
> 这个是不是每次直接把redis里面取出的任务多然后再分发任务,还是每次用的时候才从redis取，我每次往redis某个队列一次推送一万多任务,然后一启动没有一分钟任务就没有了,毕竟我调过第三方接口,每次调用也得快一秒时间,按理一工作线程的配置一万多任务也得几个小时才弄完，用过think-queue，处理5000任务要一个多小时

你可以用sleep函数测试一下
