### ISSUE TITLE
联系方式

### ISSUE THREAD

**Issue by elderhammer** [yuntian001/multi-process-queue#2]
请问联系方式是啥？有问题请教下。:-)

**Comment by yuntian001** [comment]
有问题直接在issues中直接提出即可

**Comment by elderhammer** [comment]
您好，我已收到您的邮件。我将尽快给您回复。

**Comment by elderhammer** [comment]
> 有问题直接在issues中直接提出即可

分布式部署的设计思路是什么？例如支不支持弹性伸缩，用什么实现的？

**Comment by yuntian001** [comment]
> > 有问题直接在issues中直接提出即可
> 
> 分布式部署的设计思路是什么？例如支不支持弹性伸缩，用什么实现的？
不同服务共用同一redis,分布式部署后操作同一数据库。弹性伸缩需要自己实现。
