### ISSUE TITLE
启动后CPU100%

### ISSUE THREAD

**Issue by wuaidajiejie** [yuntian001/multi-process-queue#4]
请问下大佬，`php mp-queue worker:start` 后CPU直接跑满了，我用的腾讯云1核2G的，这是正常的吗，queue数组就一个任务队列worker_number设置的2

**Comment by yuntian001** [comment]
1核2G的服务器有点差，
分发模式下 等待任务期间 worker进程几乎不占用资源，所以调低worker_number无效。可以调大监视进程休眠时间（秒，最小到0.001）

**Comment by yuntian001** [comment]
master进程有资源占用过高bug 下个版本修复

**Comment by wuaidajiejie** [comment]
我跟踪了下master进程发现一直在调用epoll_wait，从而导致CPU100%
![image](https://user-images.githubusercontent.com/65920903/162377996-138d828f-2e0b-43f4-8d2d-a47e5e2e0222.png)

**Comment by yuntian001** [comment]
已修复并发布版本.
